# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: *
  pull_request:
    branches: *

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

#    - name: Build AMD64
#      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o linux_amd64_steam_discound_tracker_for_discord main.go
#
#    - name: Build ARM64
#      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-w -s" -o linux_arm64_steam_discound_tracker_for_discord main.go
#    - name: Run GoReleaser
#      uses: goreleaser/goreleaser-action@v5
#      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
#        distribution: goreleaser
#        version: latest
#        args: release --clean
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
        # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
    - name: Release Go binary
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}