name: Image

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.IROSTUB_DOCKERHUB_USERNAME }}
          password: ${{ secrets.IROSTUB_DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.IROSTUB_DOCKERHUB_USERNAME }}/steam_discount_tracker_for_discord:${{ steps.vars.outputs.tag }} , ${{ secrets.IROSTUB_DOCKERHUB_USERNAME }}/steam_discount_tracker_for_discord:latest
